export const ADD_ONE_MILLION_TODOS = 'ADD_ONE_MILLION_TODOS'
export const ADD_ONE_TODO = 'ADD_ONE_TODO';
export const MARK_COMPLETED = 'MARK_COMPLETED';
export const MARK_NOT_COMPLETED = 'MARK_NOT_COMPLETED';